<a href="https://colab.research.google.com/github/kayeneii/AISOC-Tutorials/blob/main/AISOC_Vector_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy
from numpy import array

In [3]:
v1 = array([1,2,3,4,5])
v2 = array([3,4,6,7,9])

##Vector Arithmetics
When adding vectors together, both vectors must have the same length else you get a broadcast issue


In [4]:
v1 + v2

array([ 4,  6,  9, 11, 14])

In [5]:
v1 - v2

array([-2, -2, -3, -3, -4])

In [6]:
v1 * v2

array([ 3,  8, 18, 28, 45])

In [8]:
v2 / v1

array([3.  , 2.  , 2.  , 1.75, 1.8 ])

In [10]:
###say we have a scalar that's equal to 3
s=3
s*v1

array([ 3,  6,  9, 12, 15])

In [11]:
###to get dot product
v1.dot(v2)

np.int64(102)

In [12]:
###OR
def my_dot(a,b):
    sum = 0
    for i,j in zip(a,b):
        sum += i*j
    return sum
my_dot(v1,v2)

np.int64(102)

##Vector Norms
- $L^1$ Norm - $||v||_1$: This is the sum of the absolute vector values and is also known as the _Manhattan Norm._ Used for **Lasso Regression**.<br>

  Formula:
  
  $L^1$($v$) = $||v||_1$ = $|a|_1$ + $|a|_2$ + $|a|_3$<br>

- $L^2$ Norm - $||v||_2$: Also called the _Euclidean Norm,_ it is the root sum of all squared vector values. Used for **Ridge Regression**.<br>
  
  Formula:

   $L^2$($v$) = $||v||_2$ = $\sqrt{(|a|_1^2 + |a|_2^2 + |a|_3^2)}$<br>

*Note: A vector with all zeros is an origin: v = (0,0,0)*

In [14]:
from numpy.linalg import norm

In [15]:
v3 = v1 - v2
v3

array([-2, -2, -3, -3, -4])

In [16]:
##L^1 Norm
v3_norm = norm(v3,1)
v3_norm

np.float64(14.0)

In [19]:
##L^2 Norm
v3_norm_2 = norm(v3)
v3_norm_2

np.float64(6.48074069840786)

###Max Norm
We continue norms up to an arbitrary number of values up to infinity. When we get to $L^∞$, we have what is called the **Max Norm**.

Formula:

$L^∞$ of $||v||_3$ is<br>
$||v3||_∞$ = $\sqrt[\infty]{(|a|_1^\infty + |a|_2^\infty + |a|_3^\infty)}$

In [20]:
norm(v3,20)

np.float64(4.00126505813936)

In [21]:
from math import inf
norm(v3,inf)

np.float64(4.0)

In [22]:
print(v2)
norm(v2,inf)

[3 4 6 7 9]


np.float64(9.0)

###Nth Norm
Formula:<br>
$L^n$ = $||v3||_n$ = $\sqrt[n]{(|a|_1^n + |a|_2^n + |a|_3^n)}$